services:
  mysql:
    image: mysql:8.3.0
    container_name: order-service-mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: order_service
#      MYSQL_USER: test
#      MYSQL_PASSWORD: test
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pexamplepassword" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: