services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory-service-mysql
    restart: always
    ports:
      - "3316:3306"
    volumes:
      - ./mysql:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: inventory_service
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-pmysql" ]
      interval: 10s
      timeout: 5s
      retries: 5
